### ISSUE TITLE
Infografia_Unidad 1

### ISSUE THREAD

**Issue by Elisahadad** [SistemasTecTlaxiaco/actividad-1-infografia-Elisahadad-1#1]
[Infografía_1.Analisis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Elisahadad-1/files/14241754/Infografia_1.Analisis.pdf)

**Comment by Luz1727** [comment]
Calificacion: 20 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
